product/movies/movieapp/urls.py
from unicodedata import name
from django.urls import path
from . import views
app_name='movieapp'


urlpatterns = [
    path('', views.index, name="index"),
    path('movies/<int:id>/', views.show_details, name='detail'),  # Use name="detail"

    path('add/',views.add_movies,name="addmovie"),
    path('edit/<int:movie_id>/', views.update_movies, name="update"),

    path('delete/<int:id>/', views.delete, name='delete'),



]

product/movies/movies/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/movies/movieapp/models.py
from django.db import models

class Movies(models.Model):
    name=models.CharField(max_length=50)
    desc=models.TextField(max_length=100)
    img=models.ImageField(upload_to='images')


    def __str__(self):
        return self.name

product/movies/movieapp/forms.py
from django import forms
from .models import Movies

class MovieForm(forms.ModelForm):

    class Meta:
        model = Movies
        fields = ['name', 'desc', 'img']

product/movies/movieapp/views.py
from django.http import JsonResponse, HttpResponse
from django.shortcuts import redirect, render, get_object_or_404
from .forms import MovieForm  # Update the import statement here
from .models import Movies



def show_details(request, id):
    movie = get_object_or_404(Movies, id=id)  # Get the movie by ID
    return render(request, 'details.html', {'movie': movie})  # Pass 'movie' as a single object


def index(request):
    movies = Movies.objects.all()

    return render(request, 'index.html', {'movie_list': movies})


def add_movies(request):
    if request.method == "POST":
        name = request.POST.get("name")
        img = request.FILES["img"]
        desc = request.POST.get("desc")
        movie = Movies(name=name, img=img, desc=desc)
        movie.save()
        return redirect('movieapp:index')

    return render(request,'addmovie.html')



def update_movies(request, movie_id):
    movie = get_object_or_404(Movies, id=movie_id)

    if request.method == 'POST':
        form = MovieForm(request.POST, request.FILES, instance=movie)  # Handle file uploads
        if form.is_valid():
            form.save()
            print("Form is valid, movie updated")  # This line added for debugging
            return redirect('movieapp:index')
        else:
            print("Form is not valid, errors:", form.errors)  # This line added for debugging
    else:
        form = MovieForm(instance=movie)

    return render(request, 'edit.html', {'form': form, 'movie': movie})


def delete(request, id):
    if request.method == "POST":
        movie = Movies.objects.get(id=id)
        movie.delete()
        return redirect('movieapp:index')  # Redirect to the movie list page or any other appropriate page
    return render(request, 'delete.html')

product/movies/templates/addmovie.html
{% extends 'base.html' %}

{% block content %}
 <h3 style="padding-left:450px;">Add Movies Here</h3><br><br>
<div class="container">
    <div class="row">

        <div class="col=md-6" style="padding-left:400px;">
            <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <input type="text" name="name" class="input_class" placeholder="enter the name"> <br><br>
    <input type="text" name="desc" class="input_class" placeholder="enter the description"><br><br>
    <input type="file" name="img" class="input_class" placeholder="enter the image"><br><br>
    <button class="btn btn-secondary" type="submit">add</button>
</form>

        </div>
    </div>


</div>




{% endblock %}

product/movies/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'base.css' %}">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">MovieHouse</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'movieapp:addmovie' %}">add <span class="sr-only">(current)</span></a>
      </li>
       <li class="nav-item active">
        <a class="nav-link" href="{% url 'movieapp:index' %}">home <span class="sr-only">(current)</span></a>

      </li>



    </ul>
  </div>
</nav>
{% block content%}
{% endblock %}

</body>
</html>

product/movies/templates/delete.html
{% extends 'base.html' %}
{% block content %}
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    delete?
    <button type="submit">submit</button>
</form>
{% endblock %}

product/movies/templates/details.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <div class="row">

    <div class="col-md-6 col-gap" >
         <img src="{{ movie.img.url }}" alt="{{ movie.name }}" height="500px" width="500px">

        </div>
            <div class="col-md-6 col-gap">
                 <p>Movie ID: {{ movie.id }}</p>
                <p>Movie Name: {{ movie.name }}</p>
                 <p>Description: {{ movie.desc }}</p><br><br>
                 <a href="{% url 'movieapp:update' movie.id %}"><button type="button" class="btn btn-light" >update</button></a>
                <a href="{% url 'movieapp:delete' movie.id %}"><button type="button" class="btn btn-light" >delete</button></a>

            </div>









  </div>
</div>


{% endblock %}

product/movies/templates/edit.html
{% extends 'base.html' %}
{% block content %}
<form action="" method="post" enctype="multipart/form-data">

    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
</form>
{% endblock %}

product/movies/templates/index.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        {% for i in movie_list %}
        <div class="col-md-3">
            <div class="card"  >
  <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap"  height="790px">
  <div class="card-body" >
    <h5 class="card-title" >{{i.name}}</h5>

    <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary">Show Details</a>
  </div>
</div>
        </div>
        {% endfor %}
    </div>
</div>





{% endblock %}